package com.zitego.sql;

import java.sql.*;
import java.util.Properties;
import java.util.concurrent.Executor;

/**
 * This class is just a wrapper around a vendor's connection object that is used to intercept calls close()
 * so that the pooled connection can be returned to the pool.  All other methods are passthroughs to the wrapped
 * connection, thus in order to use methods in this class, the wrapped connection must be of a jdbc version
 * that supports the method.
 *
 * @author John Glorioso
 * @version $Id: Connection.java,v 1.3 2011/10/16 17:33:19 jglorioso Exp $
 */
public class Connection implements java.sql.Connection
{
    /** The internal connection object. */
    protected java.sql.Connection _conn;
    /** Whether the connection has been closed. */
    protected boolean _beenClosed = false;
    /** The connection factory. */
    protected ConnectionFactory _factory;

    /**
     * Wrap the supplied connection.
     *
     * @param connection
     */
    public Connection(java.sql.Connection connection)
    {
        _conn = connection;
    }

    /**
     * Wrap the supplied connection.
     *
     * @param connection
     * @param factory
     */
    public Connection(java.sql.Connection connection, ConnectionFactory factory)
    {
        _conn = connection;
        _factory = factory;
    }

    @Override
    public boolean isClosed()
    {
        return _beenClosed;
    }

    @Override
    public Statement createStatement() throws SQLException
    {
        return _conn.createStatement();
    }

    @Override
    public Statement createStatement(int resultSetType, int resultSetConcurrency) throws SQLException
    {
        return _conn.createStatement(resultSetType, resultSetConcurrency);
    }

    @Override
    public Statement createStatement(int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException
    {
        return _conn.createStatement(resultSetType, resultSetConcurrency,resultSetHoldability);
    }

    @Override
    public java.util.Map getTypeMap() throws SQLException
    {
        return _conn.getTypeMap();
    }

    @Override
    public void setTypeMap(java.util.Map map) throws SQLException
    {
        _conn.setTypeMap(map);
    }

    @Override
    public PreparedStatement prepareStatement(String stmt) throws SQLException
    {
        return new PreparedStatement( _conn.prepareStatement(stmt) );
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency) throws SQLException
    {
        return new PreparedStatement( _conn.prepareStatement(sql, resultSetType, resultSetConcurrency) );
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability)
    throws SQLException
    {
        return new PreparedStatement( _conn.prepareStatement(sql, resultSetType, resultSetConcurrency, resultSetHoldability) );
    }

    public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException
    {
        return new PreparedStatement( _conn.prepareStatement(sql, autoGeneratedKeys) );
    }

    @Override

    public PreparedStatement prepareStatement(String sql, int[] columnIndexes) throws SQLException
    {
        return new PreparedStatement( _conn.prepareStatement(sql, columnIndexes) );
    }

    @Override
    public PreparedStatement prepareStatement(String sql, String[] columnNames) throws SQLException
    {
        return new PreparedStatement( _conn.prepareStatement(sql, columnNames) );
    }

    @Override
    public CallableStatement prepareCall(String call) throws SQLException
    {
        return _conn.prepareCall(call);
    }

    @Override
    public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency) throws SQLException
    {
        return _conn.prepareCall(sql, resultSetType, resultSetConcurrency);
    }

    @Override
    public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability)
    throws SQLException
    {
        return _conn.prepareCall(sql, resultSetType, resultSetConcurrency,resultSetHoldability);
    }

    @Override
    public DatabaseMetaData getMetaData() throws SQLException
    {
        return _conn.getMetaData();
    }

    public void clearWarnings() throws SQLException
    {
        _conn.clearWarnings();
    }

    @Override
    public void setHoldability(int holdability) throws SQLException
    {
        _conn.setHoldability(holdability);
    }

    @Override
    public int getHoldability() throws SQLException
    {
        return _conn.getHoldability();
    }

    @Override
    public Savepoint setSavepoint() throws SQLException
    {
        return _conn.setSavepoint();
    }

    @Override
    public Savepoint setSavepoint(String name) throws SQLException
    {
        return _conn.setSavepoint(name);
    }

    @Override
    public void close() throws SQLException
    {
        try
        {
            try
            {
                commit();
            }
            catch(SQLException ignored) { }

            ConnectionFactory factory = _factory;
            if (factory == null) factory = ConnectionFactory.getInstance();
            if (factory != null) factory.returnConnection(this);
            _beenClosed = true;
        }
        catch (Exception e)
        {
            throw new SQLException( new StringBuffer("Could not release connection to pool:\n").append(e).toString() );
        }
    }

    @Override
    public void commit() throws SQLException
    {
        _conn.commit();
    }

    @Override
    public void finalize()
    {
        try
        {
            super.finalize();
        } catch (Throwable ex) { }
        try
        {
            if ( !isClosed() ) close();
        }
        catch (Exception ex) { }
    }

    @Override
    public boolean getAutoCommit() throws SQLException
    {
        return _conn.getAutoCommit();
    }

    @Override
    public String getCatalog() throws SQLException
    {
        return _conn.getCatalog();
    }

    @Override
    public int getTransactionIsolation() throws SQLException
    {
        return _conn.getTransactionIsolation();
    }

    @Override
    public SQLWarning getWarnings() throws SQLException
    {
        return _conn.getWarnings();
    }

    @Override
    public boolean isReadOnly() throws SQLException
    {
        return _conn.isReadOnly();
    }

    @Override
    public String nativeSQL(String string) throws SQLException
    {
        return _conn.nativeSQL(string);
    }

    @Override
    public void rollback() throws SQLException
    {
        _conn.rollback();
    }

    @Override
    public void rollback(Savepoint savepoint) throws SQLException
    {
        _conn.rollback(savepoint);
    }

    @Override
    public void releaseSavepoint(Savepoint savepoint) throws SQLException
    {
        _conn.releaseSavepoint(savepoint);
    }

    @Override
    public void setAutoCommit(boolean flag) throws SQLException
    {
        _conn.setAutoCommit(flag);
    }

    @Override
    public void setCatalog(String string) throws SQLException
    {
        _conn.setCatalog(string);
    }

    @Override
    public void setReadOnly(boolean flag) throws SQLException
    {
        _conn.setReadOnly(flag);
    }

    public void setTransactionIsolation(int i) throws SQLException
    {
        _conn.setTransactionIsolation(i);
    }

    @Override
    public Struct createStruct(String typeName, Object[] attributes) throws SQLException
    {
        return _conn.createStruct(typeName, attributes);
    }

    @Override
    public Array createArrayOf(String typeName, Object[] elements) throws SQLException
    {
        return _conn.createArrayOf(typeName, elements);
    }

    public Properties getClientInfo() throws SQLException
    {
        return _conn.getClientInfo();
    }

    @Override
    public String getClientInfo(String name) throws SQLException
    {
        return _conn.getClientInfo(name);
    }

    @Override
    public void setClientInfo(Properties props) throws SQLClientInfoException
    {
        _conn.setClientInfo(props);
    }

    @Override
    public void setClientInfo(String name, String prop) throws SQLClientInfoException
    {
        _conn.setClientInfo(name, prop);
    }

    @Override
    public boolean isValid(int timeout) throws SQLException
    {
        return _conn.isValid(timeout);
    }

    @Override
    public SQLXML createSQLXML() throws SQLException
    {
        return _conn.createSQLXML();
    }

    @Override
    public NClob createNClob() throws SQLException
    {
        return _conn.createNClob();
    }

    public Blob createBlob() throws SQLException
    {
        return _conn.createBlob();
    }

    @Override
    public Clob createClob() throws SQLException
    {
        return _conn.createClob();
    }

    @Override
    public boolean isWrapperFor(Class<?> iface) throws SQLException
    {
        return _conn.isWrapperFor(iface);
    }

    @Override
    public <T> T unwrap(Class<T> iface) throws SQLException
    {
        return _conn.unwrap(iface);
    }

    public int getNetworkTimeout() throws SQLException
    {
        return _conn.getNetworkTimeout();
    }

    public void setNetworkTimeout(Executor ex, int timeout) throws SQLException
    {
        _conn.setNetworkTimeout(ex, timeout);
    }

    @Override
    public void abort(Executor ex) throws SQLException
    {
        _conn.abort(ex);
    }

    @Override
    public void setSchema(String schema) throws SQLException
    {
        _conn.setSchema(schema);
    }

    @Override
    public String getSchema() throws SQLException
    {
        return _conn.getSchema();
    }

    public void destroy()
    {
        try
        {
            close();
        }
        catch(SQLException ignored) { }
    }
}
